package com.drozda.battlecity.unitx.enumeration;

/**
 * Created by GFH on 22.11.2015.
 */
public enum YabcType {
    TILE_BRICK,
    TILE_WATER,
    TILE_FOREST,
    TILE_ICE,
    TILE_STEEL,
    UNIT_FIRST_PLAYER,
    UNIT_SECOND_PLAYER,
    UNIT_SIMPLE_ENEMY,
    UNIT_FAST_ENEMY,
    UNIT_POWER_ENEMY,
    UNIT_ARMOR_ENEMY,
    UNIT_SIMPLE_ENEMY_X,
    UNIT_FAST_ENEMY_X,
    UNIT_POWER_ENEMY_X,
    UNIT_ARMOR_ENEMY_X,
    UNIT_ENEMY_BULLET,
    UNIT_PLAYER_BULLET,
    POSITION_ENEMY_RESPAWN,
    POSITION_FIRST_PLAYER_RESPAWN,
    POSITION_SECOND_PLAYER_RESPAWN,
    POSITION_EAGLE_BASE_RESPAWN,
    POSITION_SPADE_ZONE
}
